services:
  db:
    image: postgres:latest
    container_name: manage_me
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  cache:
    image: valkey/valkey:8-alpine
    container_name: manage_me_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --save 60 1 --loglevel warning

# Docker Compose enforces a strict rule: You cannot mount a named storage volume to a container unless you explicitly "register" the name at the very bottom of the file
volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local
